# Generated by Django 4.2 on 2023-04-18 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investment_sum', 'Какую сумму необходимо инвестировать ежемесячно в течение'), ('sum_rent', 'Какую сумму ежемесячной ренты'), ('age_rent', 'В каком возрасте я смогу получить ренту'), ('invest_year', 'С какой годовой доходностью я должен инвестировать')], max_length=254, verbose_name='Вариант вопроса инвестиционных целей')),
                ('is_removed', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('period_monthly_invest', models.IntegerField(default=0, verbose_name='период активного ежемесячного инвестирования')),
                ('start_data_invest', models.DateField(blank=True, null=True, verbose_name='дата начала инвестирования')),
                ('age_goal_achievement', models.PositiveIntegerField(blank=True, null=True, verbose_name='планируемый возраст достижения цели')),
                ('year_achievement_goal', models.DateField(blank=True, null=True, verbose_name='год достижения цели')),
                ('average_sum', models.IntegerField(blank=True, null=True, verbose_name='средняя годовая доходность инвестирования')),
                ('percent_rent_month', models.IntegerField(blank=True, null=True, verbose_name='% ежемесячной ренты по достижению возраста')),
                ('sum_rent_month', models.IntegerField(blank=True, null=True, verbose_name='размер ежемесячной ренты')),
            ],
            options={
                'verbose_name': 'Инвестиционная цель',
                'verbose_name_plural': 'Инвестиционные цели',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='возраст')),
                ('initial_sum', models.PositiveIntegerField(help_text='начальный капитал')),
                ('other_info', models.CharField(blank=True, help_text='другая информация', max_length=254, null=True)),
                ('investment_purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_purpose_list', to='settlement_plan.investmentpurpose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('name', models.CharField(max_length=50)),
                ('active_sum', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвестиционный портфель',
                'verbose_name_plural': 'Инвестиционные портфели',
            },
        ),
    ]
