# Generated by Django 4.2 on 2023-04-19 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default=datetime.date(2023, 4, 19))),
                ('currency', models.CharField(choices=[('RUB', 'рубль'), ('USD', 'доллар'), ('EUR', 'евро')], max_length=3, verbose_name='валюта')),
                ('fact_price', models.IntegerField(verbose_name='Фактическая стоимость портфеля на начало года')),
                ('plan_price', models.IntegerField(verbose_name='Планируемая стоимость портфеля на начало года')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='возраст')),
                ('initial_sum', models.PositiveIntegerField(help_text='начальный капитал')),
                ('type', models.CharField(choices=[('investment_sum', 'Какую сумму необходимо инвестировать ежемесячно в течение'), ('sum_rent', 'Какую сумму ежемесячной ренты'), ('age_rent', 'В каком возрасте я смогу получить ренту'), ('invest_year', 'С какой годовой доходностью я должен инвестировать')], max_length=254, verbose_name='Вариант вопроса инвестиционных целей')),
                ('period_monthly_invest', models.IntegerField(default=0, verbose_name='период активного ежемесячного инвестирования')),
                ('start_data_invest', models.DateField(blank=True, null=True, verbose_name='дата начала инвестирования')),
                ('age_goal_achievement', models.PositiveIntegerField(blank=True, null=True, verbose_name='планируемый возраст достижения цели')),
                ('year_achievement_goal', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='год достижения цели')),
                ('average_sum', models.IntegerField(blank=True, null=True, verbose_name='средняя годовая доходность инвестирования')),
                ('percent_rent_month', models.IntegerField(blank=True, null=True, verbose_name='% ежемесячной ренты по достижению возраста')),
                ('sum_rent_month', models.IntegerField(blank=True, null=True, verbose_name='размер ежемесячной ренты')),
                ('investment_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_purposes', to='settlement_plan.investmentportfolio')),
            ],
            options={
                'verbose_name': 'Инвестиционная цель',
                'verbose_name_plural': 'Инвестиционные цели',
            },
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('monthly_payment_plan', models.IntegerField(default=0, verbose_name='Ежемесячный взнос план')),
                ('monthly_payment_fact', models.IntegerField(default=0, verbose_name='Ежемесячный взнос Факт')),
                ('invested_funds_plan', models.IntegerField(default=0, verbose_name='Вложено средств с накопительным итогом план')),
                ('invested_funds_fact', models.IntegerField(default=0, verbose_name='Вложено средств с накопительным итогом Факт')),
                ('portfolio_value_end_month_plan', models.IntegerField(default=0, verbose_name='Стоимость портфеля на конец месяца план')),
                ('portfolio_value_end_month_fact', models.IntegerField(default=0, verbose_name='Стоимость портфеля на конец месяца Факт')),
                ('average_monthly_value_plan', models.IntegerField(default=0, verbose_name='Среднемесячная доходность план')),
                ('average_monthly_value_fact', models.IntegerField(default=0, verbose_name='Среднемесячная доходность Факт')),
                ('profit_month_plan', models.IntegerField(default=0, verbose_name='Прибыль за месяц план')),
                ('profit_month_fact', models.IntegerField(default=0, verbose_name='Прибыль за месяц Факт')),
                ('loss_month_plan', models.IntegerField(default=0, verbose_name='Убыток за месяц план')),
                ('loss_month_fact', models.IntegerField(default=0, verbose_name='Убыток за месяц Факт')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='settlement_plan.investmentportfolio')),
            ],
        ),
    ]
