# Generated by Django 4.2 on 2023-04-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentpurpose',
            name='investment_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement_plan.investmentportfolio'),
        ),
    ]
