# Generated by Django 4.2 on 2023-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_plan', '0002_investmentpurpose_investment_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentpurpose',
            name='year_achievement_goal',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='год достижения цели'),
        ),
    ]
