# Generated by Django 4.2 on 2023-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_plan', '0003_alter_investmentpurpose_year_achievement_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentpurpose',
            name='investment_portfolio',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='investment_portfolio',
            field=models.ManyToManyField(blank=True, null=True, related_name='investment_portfolio_list', to='settlement_plan.investmentportfolio'),
        ),
    ]
