# Generated by Django 4.2 on 2023-04-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement_plan', '0004_remove_investmentpurpose_investment_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='investment_portfolio',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='investment_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investment_portfolio_list', to='settlement_plan.investmentportfolio'),
        ),
    ]
