# Generated by Django 4.2 on 2023-04-18 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settlement_plan', '0005_remove_userinfo_investment_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio', to=settings.AUTH_USER_MODEL),
        ),
    ]
